//auth
export const GET_AUTH_FEED: 'GET_AUTH_FEED' = 'GET_AUTH_FEED';

export const GET_AUTH_FEED_FAILED: 'GET_AUTH_FEED_FAILED' =
  'GET_AUTH_FEED_FAILED';

export const GET_AUTH_FEED_SUCCESS: 'GET_AUTH_FEED_SUCCESS' =
  'GET_AUTH_FEED_SUCCESS';

//constructor
export const SET_CONSTRUCTOR: 'SET_CONSTRUCTOR' = 'SET_CONSTRUCTOR';

export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' =
  'DELETE_CONSTRUCTOR_INGREDIENT';

export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' =
  'ADD_CONSTRUCTOR_INGREDIENT';

export const SORT_CONSTRUCTOR_INGREDIENTS: 'SORT_CONSTRUCTOR_INGREDIENTS' =
  'SORT_CONSTRUCTOR_INGREDIENTS';

//user
export const GET_USER_INFO_FEED: 'GET_USER_INFO_FEED' = 'GET_USER_INFO_FEED';

export const GET_USER_INFO_FEED_FAILED: 'GET_USER_INFO_FEED_FAILED' =
  'GET_USER_INFO_FEED_FAILED';

export const GET_USER_INFO_FEED_SUCCESS: 'GET_USER_INFO_FEED_SUCCESS' =
  'GET_USER_INFO_FEED_SUCCESS';

export const CHANGE_USER_INFO_FEED: 'CHANGE_USER_INFO_FEED' =
  'CHANGE_USER_INFO_FEED';

export const CHANGE_USER_INFO_FEED_FAILED: 'CHANGE_USER_INFO_FEED_FAILED' =
  'CHANGE_USER_INFO_FEED_FAILED';

export const CHANGE_USER_INFO_FEED_SUCCESS: 'CHANGE_USER_INFO_FEED_SUCCESS' =
  'CHANGE_USER_INFO_FEED_SUCCESS';

export const GET_TOKEN_FEED: 'GET_TOKEN_FEED' = 'GET_TOKEN_FEED';

export const GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS' = 'GET_TOKEN_SUCCESS';

export const GET_TOKEN_FAILED: 'GET_TOKEN_FAILED' = 'GET_TOKEN_FAILED';

//logout

export const GET_LOGOUT_FEED: 'GET_LOGOUT_FEED' = 'GET_LOGOUT_FEED';

export const GET_LOGOUT_FEED_FAILED: 'GET_LOGOUT_FEED_FAILED' =
  'GET_LOGOUT_FEED_FAILED';

export const GET_LOGOUT_FEED_SUCCESS: 'GET_LOGOUT_FEED_SUCCESS' =
  'GET_LOGOUT_FEED_SUCCESS';

//ingredients

export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' =
  'SET_CURRENT_INGREDIENT';

export const DELETE_CURRENT_INGREDIENT: 'DELETE_CURRENT_INGREDIENT' =
  'DELETE_CURRENT_INGREDIENT';

export const GET_INGREDIENT_FEED: 'GET_INGREDIENT_FEED' = 'GET_INGREDIENT_FEED';

export const GET_INGREDIENT_FEED_FAILED: 'GET_INGREDIENT_FEED_FAILED' =
  'GET_INGREDIENT_FEED_FAILED';

export const GET_INGREDIENT_FEED_SUCCESS: 'GET_INGREDIENT_FEED_SUCCESS' =
  'GET_INGREDIENT_FEED_SUCCESS';

export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';

//reset-password

export const GET_RESET_CODE_FEED: 'GET_RESET_CODE_FEED' = 'GET_RESET_CODE_FEED';

export const GET_RESET_CODE_FAILED: 'GET_RESET_CODE_FAILED' =
  'GET_RESET_CODE_FAILED';

export const GET_RESET_CODE_SUCCESS: 'GET_RESET_CODE_SUCCESS' =
  'GET_RESET_CODE_SUCCESS';

export const GET_RESET_PASSWORD_FEED: 'GET_RESET_PASSWORD_FEED' =
  'GET_RESET_PASSWORD_FEED';

export const GET_RESET_PASSWORD_FAILED: 'GET_RESET_PASSWORD_FAILED' =
  'GET_RESET_PASSWORD_FAILED';

export const GET_RESET_PASSWORD_SUCCESS: 'GET_RESET_PASSWORD_SUCCESS' =
  'GET_RESET_PASSWORD_SUCCESS';

//order
export const GET_ORDER_FEED: 'GET_ORDER_FEED' = 'GET_ORDER_FEED';

export const GET_ORDER_FEED_FAILED: 'GET_ORDER_FEED_FAILED' =
  'GET_ORDER_FEED_FAILED';

export const GET_ORDER_FEED_SUCCESS: 'GET_ORDER_FEED_SUCCESS' =
  'GET_ORDER_FEED_SUCCESS';

export const FEED_WS_CONNECTION_START: 'FEED_WS_CONNECTION_START' =
  'FEED_WS_CONNECTION_START';

export const FEED_WS_CONNECTION_SUCCESS: 'FEED_WS_CONNECTION_SUCCESS' =
  'FEED_WS_CONNECTION_SUCCESS';

export const FEED_WS_CONNECTION_ERROR: 'FEED_WS_CONNECTION_ERROR' =
  'FEED_WS_CONNECTION_ERROR';

export const FEED_WS_GET_MESSAGE: 'FEED_WS_GET_MESSAGE' = 'FEED_WS_GET_MESSAGE';

export const FEED_WS_CLOSE_CONNECTION: 'FEED_WS_CLOSE_CONNECTION' =
  'FEED_WS_CLOSE_CONNECTION';

export const FEED_WS_CONNECTION_CLOSED: 'FEED_WS_CONNECTION_CLOSED' =
  'FEED_WS_CONNECTION_CLOSED';

export const SET_CURRENT_ORDER: 'SET_CURRENT_ORDER' = 'SET_CURRENT_ORDER';

export const DELETE_CURRENT_ORDER: 'DELETE_CURRENT_ORDER' =
  'DELETE_CURRENT_ORDER';
